title: Innershell Labs
description: Deep security reviews, systems analysis, and adversarial thinking on complex infrastructures.
author: Diego Concha
logo: /assets/img/logo.svg
footer_logo: /assets/img/logo.svg